server:
  port: 9008
spring:
  application:
    name: socialbinary-web #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:9006/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    socialbinary-gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: socialbinary-gathering #指定Eureka注册中心中的服务id
    socialbinary-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: socialbinary-article #指定Eureka注册中心中的服务id
    socialbinary-base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: socialbinary-base #指定Eureka注册中心中的服务id
#    socialbinary-friend: #交友
#      path: /friend/** #配置请求URL的请求规则
#      serviceId: socialbinary-friend #指定Eureka注册中心中的服务id
    socialbinary-qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: socialbinary-qa #指定Eureka注册中心中的服务id
    socialbinary-recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: socialbinary-recruit #指定Eureka注册中心中的服务id
#    socialbinary-spit: #吐槽
#      path: /spit/** #配置请求URL的请求规则
#      serviceId: socialbinary-spit #指定Eureka注册中心中的服务id
#    socialbinary-user: #用户
#      path: /user/** #配置请求URL的请求规则
#      serviceId: socialbinary-user #指定Eureka注册中心中的服务id
#    socialbinary-search: #用户
#      path: /search/** #配置请求URL的请求规则
#      serviceId: socialbinary-search #指定Eureka注册中心中的服务id
