server:
  port: 9003
spring:
  application:
    name: socialbinary-qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9006/eureka
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
feign:
  hystrix:
    enabled: true
